### ISSUE TITLE
라운드 빼주세요! 정사각형으로

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#101]
![noround](https://cloud.githubusercontent.com/assets/22297573/22553378/d43b99d0-e99f-11e6-82b5-419b3683750c.jpeg)

![roung](https://cloud.githubusercontent.com/assets/22297573/22553379/d4680984-e99f-11e6-80b1-9f61e5d7dc3b.jpeg)

**Comment by seobew** [comment]
완료

**Comment by seobew** [comment]
socialup.kr에서 수정한거 확인했습니다.
