### ISSUE TITLE
텍스트css가 위 아래가 바뀌어야할듯! 제목은 굵게 내용은 얇게

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#102]
![bold](https://cloud.githubusercontent.com/assets/22297573/22553332/a7fb0c0c-e99f-11e6-9513-05e429ad9871.jpeg)

**Comment by seobew** [comment]
완료

**Comment by seobew** [comment]
socialup.kr에서 수정한거 확인했습니다.
