### ISSUE TITLE
join 시 배경교체

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#106]
https://drive.google.com/open?id=0B_8MhWTWBP2Fems5S3Btek1ZRmc

이거로 교체해주세요.
그리고 입력창 위쪽에 삼각형은 없애주세요!

**Comment by seobew** [comment]
완료.

**Comment by seobew** [comment]
![2017-02-06 5 37 25](https://cloud.githubusercontent.com/assets/17023044/22639767/f6079e24-ec92-11e6-8909-bc698f0e1c79.png)

이렇게 나와야 하는거 맞나요??

**Comment by oooowljoy** [comment]
맞긴한데...색감이 너무 달라서 이거 보강좀 해야할것같아요! ㅠ_ㅠ 작업할게용

**Comment by seobew** [comment]
넵넵 알겠어요

**Comment by seobew** [comment]
위에서 이슈 따로 남겨놨던거 close해서 이것도 close 할게요.
