### ISSUE TITLE
상품등록-이전기록 불러오기를 눌렀을 때 상품설명 부분이 제대로 들어가지 않음

### ISSUE THREAD

**Issue by KangHyeongMin** [springkjw/socialup#107]
<img width="1558" alt="2017-02-03 10 56 32" src="https://cloud.githubusercontent.com/assets/13078318/22593998/8eb587ca-ea64-11e6-9c97-29395c2ba369.png">
상품등록할 때 이전꺼 불러오는거에서 만약 description(상품설명. 썸머노트부분)을 건드리지 않으면(수정 또는 클릭하지 않으면) 해당 내용이 비어있다고 인식하고 등록버튼을 눌렀을 때 등록이 되지 않음. 그리고 상품설명에 불러왔던 내용이 없어짐.

**Comment by seobew** [comment]
완료.
