### ISSUE TITLE
상품등록시 포스팅가능분야 선택(태그) 중 ‘전체’와 다른 태그가 중복선택 됨

### ISSUE THREAD

**Issue by KangHyeongMin** [springkjw/socialup#108]
<img width="891" alt="2017-02-03 11 02 23" src="https://cloud.githubusercontent.com/assets/13078318/22594072/eaa5bb36-ea64-11e6-8aa0-7e4de6e09ed2.png">

'전체'를 눌렀을 때는 기존에 선택되어있던 다른 태그들이 해제되고, 다른 태그를 눌렀을 때는 '전체' 태그가 해제되도록 수정필요

**Comment by seobew** [comment]
완료.

**Comment by seobew** [comment]
socialup.kr에서 수정한거 확인했습니다.
