### ISSUE TITLE
그리드 어긋남!

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#114]
![jj](https://cloud.githubusercontent.com/assets/22297573/22632457/cf10a148-ec5c-11e6-80e6-241a4f0b80cb.jpeg)

**Comment by seobew** [comment]
여전히 저렇게 보이나요???

**Comment by KangHyeongMin** [comment]
캐시(한번 방문했던 페이지에서 레이아웃 같은 정보를 저장해두는 것)때문일 수가 있어요, 캐시, 임시파일 삭제후에 다시 접속하거나 크롬의 시크릿모드로 접속해도 여전히 같은지 확인 부탁해요!

**Comment by oooowljoy** [comment]
시크릿모드에서 보니 괜찮아요!

**Comment by KangHyeongMin** [comment]
그렇다면 해결~
