### ISSUE TITLE
message  오류 

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#116]
![default](https://cloud.githubusercontent.com/assets/22297573/22641376/d31db32e-ec99-11e6-8f6f-8fedaa87b5cc.jpeg)

**Comment by seobew** [comment]
메세지는 제가 건드리기 힘들 것 같아요..

**Comment by KangHyeongMin** [comment]
메세지 위로 튀어나와있는 것은 수정했고, 사진 제대로 안뜨는 문제는 기존에 남아있던 채팅 기록 때문일 것으로 생각합니다. 이후 생성한 아이디에는 문제 없습니다.
