### ISSUE TITLE
상품 등록 URL오류

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#127]
![2](https://cloud.githubusercontent.com/assets/22297543/22680871/bdfea868-ed4d-11e6-9a90-a32d9acadc8c.jpg)

URL을 잘못 입력했는데 이 창이 먼저 뜨고
![1](https://cloud.githubusercontent.com/assets/22297543/22680872/be5e97aa-ed4d-11e6-898d-f48cc9db3b83.jpg)

이렇게 떠요.

두번째 사진 먼저 뜨게 해야하는데 두번째도 창이 저렇게 텍스트로 뜨는 것 보다 팝업창 형식으로 떠야할 것 같아요

**Comment by seobew** [comment]
완료.
