### ISSUE TITLE
상품 등록 문제

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#128]
![1](https://cloud.githubusercontent.com/assets/22297543/22680981/43a6f0f6-ed4e-11e6-990a-83f20e7b1560.jpg)
숫자 옆에 '명'표기
![2](https://cloud.githubusercontent.com/assets/22297543/22680982/43ee1f62-ed4e-11e6-8d8f-28d82d2bfd45.jpg)
승인요청중인 상품 수정하려고 보니까
이용약관을 동의해달라고 하고 이용약관이 없음.
또 저걸 클릭하면 바로 메인페이지로 넘어가요.

![1](https://cloud.githubusercontent.com/assets/22297543/22681022/81dc0276-ed4e-11e6-8bdc-ea89245e9b48.jpg)
저렇게 하고 상품 수정이 되었음
30자 이상 입력해도 제지없이 저렇게 되는데 문자가 뜸

![1](https://cloud.githubusercontent.com/assets/22297543/22681100/dcb8146e-ed4e-11e6-8b7c-c4a02171559f.jpg)

상품관리에 있는 X버튼 눌렀는데 바로 없어지면서 이렇게 떴어요 ㅜㅜ
힘들게 썼는데 확인 취소 없이 바로 없어져 버림 ㅜㅜ
꼭 삭제하겠습니다 팝업 뜨게 해주세요!

**Comment by seobew** [comment]
완료.
