### ISSUE TITLE
적립금 보여주기

### ISSUE THREAD

**Issue by KangHyeongMin** [springkjw/socialup#129]
<img width="246" alt="2017-02-07 4 02 32" src="https://cloud.githubusercontent.com/assets/13078318/22681120/f3d8786e-ed4e-11e6-8c48-ea2a62fed8e2.png">
포인트 옆에 적립금도 표시해주기

**Comment by KangHyeongMin** [comment]
조이 디자인 부탁합니당!

**Comment by oooowljoy** [comment]
네에~!
![mypage_buyer_](https://cloud.githubusercontent.com/assets/22297573/22720852/d3e4dd16-edf0-11e6-9686-100924f810ec.png)

**Comment by KangHyeongMin** [comment]
완료
