### ISSUE TITLE
login/join 배경이미지 변경해주세요~~

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#133]
https://drive.google.com/open?id=0B_8MhWTWBP2Fd2VHTVZiWkVYTms

bg_01은 join시,
bg_02는 login시!
![00](https://cloud.githubusercontent.com/assets/22297573/22686819/fb6da864-ed68-11e6-95b7-f0424fcde804.jpeg)
여기 이미지는 bg_03으로 교체해주세용,그리고 확인 버튼 round없애주세요

+로그인시/이메일인증 시 소셜업 로고인 삼각형 빼주세요!

**Comment by seobew** [comment]
완료.
