### ISSUE TITLE
배경교체 및 버튼 형태 변경

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#135]
![000](https://cloud.githubusercontent.com/assets/22297573/22686953/8bf0571a-ed69-11e6-8bed-cd06fe927a0d.jpeg)

배경 bg_03으로 교체
https://drive.google.com/drive/folders/0B_8MhWTWBP2Fd2VHTVZiWkVYTms?usp=sharing

버튼 라운드빼기

**Comment by seobew** [comment]
완료.
