### ISSUE TITLE
에디터 높이 좀 줄여주세요. 스크롤 안해도 박스가 다 보이도록!

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#144]
#![editor](https://cloud.githubusercontent.com/assets/22297573/22725248/a7388ff0-ee0f-11e6-963d-b9a9584e359d.jpeg)
![editor02](https://cloud.githubusercontent.com/assets/22297573/22725284/d0549870-ee0f-11e6-8a98-70ef6be99b9e.jpeg)

**Comment by seobew** [comment]
완료.
