### ISSUE TITLE
인플루언서 상세정보

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#148]
![1](https://cloud.githubusercontent.com/assets/22297543/22726425/b1c56bd0-ee16-11e6-9501-16fd46033302.jpg)

이미지에 기본값과 수정 내용 써있어요

![1](https://cloud.githubusercontent.com/assets/22297543/22726449/d2480750-ee16-11e6-9d65-ef92d164d340.jpg)
화면 작게하면 글자가 겹치네요

**Comment by seobew** [comment]
완료.
