### ISSUE TITLE
옵션 가격 default값 수정 

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#154]
![default](https://cloud.githubusercontent.com/assets/22297573/22727302/9e05054c-ee1b-11e6-858f-b360d7e7bba6.jpeg)

보통 1000원 이상부터 추가한다는 가정하에 기본값이 1000원이고 증가 버튼을 눌렀을때 100원씩 추가되도록 해주세요~

**Comment by seobew** [comment]
증가버튼은 어떻게 생겼나요??

**Comment by KangHyeongMin** [comment]
대표님과 얘기 후 placeholder(입력값 없을 때 예시)만 넣는 것으로 대체하였습니다.
