### ISSUE TITLE
버튼 라운드 제거해주세요

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#155]
**동의하고 포스팅올리기 후** 
![default](https://cloud.githubusercontent.com/assets/22297573/22727373/efb62d12-ee1b-11e6-990c-25d77eab928b.jpeg)

**마이페이지**
![02](https://cloud.githubusercontent.com/assets/22297573/22727434/31e18c04-ee1c-11e6-842a-0e04cc6991bb.jpeg)

이미지에 보이는 모든 버튼 라운드 제거해주세요!

**Comment by seobew** [comment]
테스트하면서 라운드 제거하고 있는데 못찾은게 있을 수 있으니 그런건 이렇게 올려줘요.
올려준 버튼들은 다 제거했습니다.

**Comment by oooowljoy** [comment]
넹~~~~~~
