### ISSUE TITLE
토끼이미지 랜덤하게 출력해주세요

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#156]
https://drive.google.com/open?id=0B_8MhWTWBP2FNm5Vby1OQkZEZTg
여기보면 토끼 세가지 종류있는데 카톡 프로필사진 적용안했을때 각자 랜덤하게 나오는 것처럼
할 수 있나요?!

**Comment by KangHyeongMin** [comment]
랜덤하게 보일 수는 있는데, 조이가 원하는건 가입할 때 랜덤하게 프로필 이미지가 하나로 정해지는거죠?

**Comment by oooowljoy** [comment]
네!

**Comment by KangHyeongMin** [comment]
적용확인했습니당
