### ISSUE TITLE
증감 버튼 

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#159]
https://drive.google.com/drive/folders/0B_8MhWTWBP2FeEYwV1BPUHJqaUk?usp=sharing
여기에 버튼 있어요~

**기본값**
![25](https://cloud.githubusercontent.com/assets/22297573/22731580/7336e2dc-ee2e-11e6-811d-064415fcb13f.png)

**클릭시**
![25](https://cloud.githubusercontent.com/assets/22297573/22731578/7303381a-ee2e-11e6-8deb-f9c59860fefd.png)

**Comment by KangHyeongMin** [comment]
대표님과 얘기해보니 증감버튼 필요 없을것 같아 빈칸 멘트만 설정하고 닫겠습니당
