### ISSUE TITLE
상품 승인거절했는데 승인완료 라고 뜸

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#161]
![3](https://cloud.githubusercontent.com/assets/22297543/22733750/799e808c-ee36-11e6-8b0a-64795bdbfe2c.jpg)
![2](https://cloud.githubusercontent.com/assets/22297543/22733719/541000c0-ee36-11e6-8e96-bcdbe4b4584a.jpg)

1. 승인거절 눌렀는데 승인완료라고 떠요
2. 그래프 문자가 조금 내려와요
![3](https://cloud.githubusercontent.com/assets/22297543/22733833/c8b2e1fe-ee36-11e6-8911-35e68953aad7.jpg)

3. 상품 삭제버튼이 이렇게 뜸

**Comment by seobew** [comment]
1,2 완료.

**Comment by seobew** [comment]
완료.
