### ISSUE TITLE
글자배열

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#163]
![2](https://cloud.githubusercontent.com/assets/22297543/22734307/8915d59a-ee38-11e6-8e54-0613e1406ab4.jpg)
![3](https://cloud.githubusercontent.com/assets/22297543/22734310/8a4f7c0e-ee38-11e6-8553-70a90c9b09c0.jpg)

 익스플로러 상에서 글자가 올라가 있고, 또 내려가있어요(쿠키삭제했음)

**Comment by seobew** [comment]
완료.
