### ISSUE TITLE
구매관리쪽 오류

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#164]
![2](https://cloud.githubusercontent.com/assets/22297543/22734481/33e755e8-ee39-11e6-9bad-4b0a68c47abc.jpg)

1. 거래완료의 상태인데도 구매취소 버튼이 떠요. (화면기획서 8.1.1.1.-8.1.1.1.6 참고)
2. 구매취소와 구매확정할 때 확인팝업창 뜨게 해주세요
ex) 구매를 취소하시겠습니까?
     구매를 확정하시겠습니까?

**Comment by seobew** [comment]
완료.
