### ISSUE TITLE
메인 그래프

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#166]
![1](https://cloud.githubusercontent.com/assets/22297543/22772804/22fd8578-eee2-11e6-8734-ff169c7752d6.jpg)
0.5를 입력했는데 0.50000 까지 뜨네요.
입력한 숫자로 뜨게 해주시고 단위 '원' 붙여주세요
평점 별이 내려와요

**Comment by seobew** [comment]
위에 중복 이슈가 있어서 닫겠습니다.
