### ISSUE TITLE
메인페이지 그래프

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#176]
![1](https://cloud.githubusercontent.com/assets/22297543/22784411/442cf248-ef13-11e6-8c36-4285d15d24b9.jpg)
1. 프로필 사진 크기 늘리고 아이디와 평점 두 줄로! 평점 개수 표기
2. 실제 홈페이지보면 그래프와 한줄소개가 가까워요. 좀만 떨어지게 해주세요

![1](https://cloud.githubusercontent.com/assets/22297543/22784466/7b978734-ef13-11e6-951f-614ce307420d.jpg)

3. 기획서에 있는 원고료포함/비포함, 개인/페이지, 여성/남성 표기

**Comment by seobew** [comment]
위에 비슷한 이슈가 있어서 닫겠습니다.
