### ISSUE TITLE
전체화면안하면 logi라고 나옴! 

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#177]
![000](https://cloud.githubusercontent.com/assets/22297573/22784569/e340ad84-ef13-11e6-93c3-f3943e61a46a.jpeg)

ㅠㅠ화면크기에따라 다른 출력값은 힘들겠죠..?
예를들면 화면이 작아지면 login/join 폰트크기가 작아지는...

**Comment by seobew** [comment]
화면이 작아져도 안잘리게 해놨어요!
