### ISSUE TITLE
포인트/적립금

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#178]
![1](https://cloud.githubusercontent.com/assets/22297543/22784636/3915d34c-ef14-11e6-8d85-63f3b4cd81c4.jpg)

1. 짤려나옴
![1](https://cloud.githubusercontent.com/assets/22297543/22784992/af342366-ef15-11e6-97cb-8ad5681bc981.jpg)

2. 다음과 같은 디자인으로 수정. 마일리지를 적립금으로 수정.
숫자 크기가 작아도 되니까 100만원까지 표기될 수 있을 정도로 여유

**Comment by seobew** [comment]
완료.
