### ISSUE TITLE
그래프 수정 반영안된 부분

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#181]
![1](https://cloud.githubusercontent.com/assets/22297543/22790361/4d581f3a-ef29-11e6-9cf4-efce5a7862e7.jpg)

파란 박스는 메인페이지고
빨간박스는 카테고리 메뉴 눌러서 들어간거예요.

앞에 수정한 사항이 반영안되어 있어요.
남성/여성, 원고료포함/미포함, 가격바 등

**Comment by seobew** [comment]
완료.
