### ISSUE TITLE
닫기버튼 기능 바꾸기

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#183]
![default](https://cloud.githubusercontent.com/assets/22297573/22791276/2965491a-ef2c-11e6-8750-74714ff30530.jpeg)

닫기를 눌렀더니 창을 없애는 건줄 알았는데 포스팅을 삭제하는 기능인가봐요.
팝업 닫기인줄 알고 계속그렇게 작업했더니 하나도 안올라갔더라구요. 
이 부분 급하게 수정되어야할듯해요ㅠㅠㅠㅠㅠㅠㅠㅠㅠ속상

**Comment by seobew** [comment]
완료. 닫기버튼 없앴어요
