### ISSUE TITLE
주소입력이 필수값인데 그냥 넘어갔음

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#184]
![default](https://cloud.githubusercontent.com/assets/22297573/22791403/97f0f4ce-ef2c-11e6-9fe3-e4d8841da98f.jpeg)

주소 입력이 필수인데 아까는 에러생겼다고 상단에 텍스트로 나타났는데 
지금은 또 그냥 넘어가요ㅠㅠㅠ 왔다갔다함

**Comment by seobew** [comment]
완료.
