### ISSUE TITLE
상품 관리 고칠거

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#186]
![1](https://cloud.githubusercontent.com/assets/22297543/22814925/e268040c-ef9a-11e6-84f1-9fa0c49ebbf0.jpg)
1. 게시물을 수정하면 승인중이라고 뜨는데 관리자 페이지에는 이게 승인을 해줘야하는지 안나와있네요.
관리자 페이지에 승인중, 거절된거 한눈에 보이게 해야할 것 같아요.
2. 상품번호 표기 괄호에 회색글씨로 [1231]
3. 원고 가능이 체크되어 있고 0원일 때 -원고료 포함
원고 가능이 체크되어 있고 금액이 있을 때 -원고료 별도
   원고 가능이 체크되어 있지 않을 때 - 원고작성 불가

![1](https://cloud.githubusercontent.com/assets/22297543/22815818/64444354-efa1-11e6-95a3-12cc1cad5024.jpg)

**Comment by seobew** [comment]
2,3 완료.

**Comment by KangHyeongMin** [comment]
1 완료
