### ISSUE TITLE
적립금과 포인트 중간의 선

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#191]
![1](https://cloud.githubusercontent.com/assets/22297543/22869663/0e831702-f1e4-11e6-9a1f-b84abcb2565d.jpg)

선이 어중간하게 나와요

**Comment by KangHyeongMin** [comment]
조정했습니다. 익스플로러의 경우 백만단위까지는 문제없이 출력되고 천만단위부터 줄이 내려와서 선간격이 좁아지는 문제가 있는데 추후에 수정하겠습니다. 크롬에서는 천만단위까지는 문제없습니다.
