### ISSUE TITLE
판매관리 

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#192]
![1](https://cloud.githubusercontent.com/assets/22297543/22869746/97debdbc-f1e4-11e6-8fb8-b26148dd05d1.jpg)

![1](https://cloud.githubusercontent.com/assets/22297543/22869814/4e7d4714-f1e5-11e6-86aa-f93ae01b13b7.jpg)

상품명 등 글자 배열 오류

**Comment by KangHyeongMin** [comment]
해결
