### ISSUE TITLE
작업취소할때 팝업창 띄우기

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#193]
![1](https://cloud.githubusercontent.com/assets/22297543/22869770/c6a4ee28-f1e4-11e6-82b5-afc1f145225f.jpg)

판매관리나 구매관리에서

'작업진행','작업완료','구매취소''구매확정'모두 확인 팝업창 띄어주세요.

현재 구매관리-전체 에서만 팝업창이 뜹니다.

**Comment by seobew** [comment]
완료.
