### ISSUE TITLE
sns상품 등록시 url

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#200]
![1](https://cloud.githubusercontent.com/assets/22297543/22881172/b9d402bc-f228-11e6-88a7-b79d204fef2b.jpg)

https:// 를 기본으로 해주는게 좋을 것같아요

**Comment by seobew** [comment]
![2017-02-13 8 44 05](https://cloud.githubusercontent.com/assets/17023044/22882178/39672424-f22d-11e6-8417-d80dc7819fe0.png)

기본적으로 'http://'가 나오게 해놨어요

**Comment by seobew** [comment]
https:// 로 바꿨습니다.
