### ISSUE TITLE
프로필 사진이 안바뀜

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#202]
![1](https://cloud.githubusercontent.com/assets/22297543/22881404/a1d7546a-f229-11e6-99b7-3179a98c1b6d.jpg)
프로필 사진 넣었는데 안바껴요!

![1](https://cloud.githubusercontent.com/assets/22297543/22921423/fbdd240e-f2dc-11e6-9b69-f3c54e26a7a4.jpg)

2017.02.14.17:40
현재 기본 프로필이 이렇게 뜨네요

**Comment by KangHyeongMin** [comment]
일반적인 회원가입이 아닌 경로(관리자 권한으로 계정 추가 등)로 계정을 만들면 기본프로필이 x박스로 뜹니다.
일반 회원들의 경우에는 문제 없습니다. 프로필사진 변경도 작동합니다. 프로필사진 변경이 안되는 경우는 필수 개인정보 미입력의 경우입니다. 해당 문제는 다시 이슈로 등록하겠습니다.
