### ISSUE TITLE
배너추가해주세용

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#206]
https://drive.google.com/open?id=0B_8MhWTWBP2FckRGMzVETzNzLXM
메인 배너에 이 이미지 추가해주세요!

**Comment by springkjw** [comment]
시작하기는 빼셔야할듯
@oooowljoy

**Comment by oooowljoy** [comment]
빼서 다시올렸어요!

**Comment by seobew** [comment]
시작하기 그대로 있어요!
@oooowljoy

**Comment by seobew** [comment]
완료.
