### ISSUE TITLE
포스팅 쓰기 버튼

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#212]
![12](https://cloud.githubusercontent.com/assets/22297543/22960937/485f0664-f385-11e6-9d9c-16576a2b3330.jpg)

포스팅 쓰기 -> 서비스 등록   으로 바꿔주세요
어쩔 때는 이게 나오고 어쩔 때는 안나오네요.
항시 뜨게 해주세요.

**Comment by seobew** [comment]
완료.
