### ISSUE TITLE
프로필 수정 안됨

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#213]
![12](https://cloud.githubusercontent.com/assets/22297543/22961106/cd6c694a-f386-11e6-8bbd-826209d0fc07.jpg)

1. * 표시 입력 다 안했을 때도 수정 완료 되었다고 뜹니다.  * 표시를 입력안했을 때는 '정보수정 완료' 팝업이 아니라 '* 표시로 된 필수정보를 입력해주세요.'라는 팝업창이 필요할 것 같아요.
2. 또 필수정보를 입력안했는데도 불구하고 수정이 될 때가 있습니다.

**Comment by KangHyeongMin** [comment]
해결

**Comment by seobew** [comment]
중복된 이슈가 있기때문에 닫겠습니다.
