### ISSUE TITLE
인플루언서 상세 프로필

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#214]
![-](https://cloud.githubusercontent.com/assets/22297543/22963501/cf8e6196-f396-11e6-92d8-81a8f6a66e82.jpg)

이름 추가
여성/남성으로
-년생으로

**Comment by KangHyeongMin** [comment]
완료

**Comment by KangHyeongMin** [comment]
중복되는 이슈가 있어서 닫겠습니당(issue #224 )
