### ISSUE TITLE
롸이언~~~~~

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#219]
![kakaotalk_photo_2017-02-15-17-12-43-1](https://cloud.githubusercontent.com/assets/22297573/22965664/fadd3e02-f3a1-11e6-9ffa-bd8f82278e93.png)

여기에

![ba](https://cloud.githubusercontent.com/assets/22297573/22965728/4703bb58-f3a2-11e6-88ee-bd80c38b7278.png)

이 배너 넣어주세용
배너 링크는 https://drive.google.com/open?id=0B_8MhWTWBP2Fb0hwVXJZbEdaSTg

**Comment by seobew** [comment]
완료.
