### ISSUE TITLE
상품등록 안했을 때 상품관리 누르면.

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#222]
![11](https://cloud.githubusercontent.com/assets/22297543/22970547/e66c14b6-f3b5-11e6-84c1-54bd86c63419.jpg)

지금은 이 화면 그대로 보이는데

![11](https://cloud.githubusercontent.com/assets/22297543/22970774/be6f23bc-f3b6-11e6-944a-285c0ddcc067.jpg)

이렇게 나오게 해주세용

**Comment by KangHyeongMin** [comment]
해결
