### ISSUE TITLE
이름변경이 안돼요

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#224]
![1](https://cloud.githubusercontent.com/assets/22297543/23009306/8de79b78-f458-11e6-823e-a2b0a81c5c5e.jpg)

1. 이름변경이 안되고 있네용
2. none 년생이 아니라 - 년생으로

**Comment by KangHyeongMin** [comment]
해결. None년생 부분은 배포버전에서 확인 필요

**Comment by KangHyeongMin** [comment]
None년생 문제가 아직 남아있네용. 추가 수정했으니 배포버전 반영을 기다려봅니당
