### ISSUE TITLE
가격순 바 적용

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#227]
![11](https://cloud.githubusercontent.com/assets/22297543/23009420/3ca7a432-f459-11e6-9cc0-10f1ac12dca7.jpg)

![11](https://cloud.githubusercontent.com/assets/22297543/23009557/07f41c92-f45a-11e6-8291-dacf4e36342c.jpg)
메인페이지 가격순 바가 적용안되고 있습니다. 또 카테고리를 선택해서 들어갈 때 저렇게 서비스와 바 사이에 공백이 생겨요

**Comment by seobew** [comment]
완료.
