### ISSUE TITLE
서비스 평가 부분

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#230]
![12](https://cloud.githubusercontent.com/assets/22297543/23009784/4f191734-f45b-11e6-9f88-52e4eae534ab.jpg)

1. 문자 배열이 안맞습니다.
2. 필수항목을 선택안했을 때 '필수사항을 입력해주세요.'라는 창이 뜨도록 해주세요.(선택사항은 입력안해도 됨)
3. 영어를 한글로 바꿔주세요.
4. 빨간 네모칸 넣어주세요

**Comment by KangHyeongMin** [comment]
완료
