### ISSUE TITLE
구매 고객리뷰 적용

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#237]
![12](https://cloud.githubusercontent.com/assets/22297543/23010452/db46fc6e-f45e-11e6-95d9-cbfd2f643155.jpg)

입력한 대로 적용이 안되고 있습니다.
콘텐츠 광고효과 친절도 부분은 입력안한 부분도 있고 불만족으로 체크했는데 
다 만족으로 뜨고 평가 부분은 다 none으로 뜨네요
위에 파란 그래프도 적용안되네요

**Comment by seobew** [comment]
완료.
