### ISSUE TITLE
자기소개글 입력하면 여러군데서 깨져요

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#244]
![da](https://cloud.githubusercontent.com/assets/22297543/23011656/8d59816e-f465-11e6-959d-7d8d642d7789.jpg)
서비스 상세설명에서 깨지고
![wa](https://cloud.githubusercontent.com/assets/22297543/23011657/900f371e-f465-11e6-94ec-1456036ce338.jpg)
인플루언서 프로필가서도 네모칸 영역을 늘려야 할듯요

**Comment by KangHyeongMin** [comment]
해결
