### ISSUE TITLE
상품 등록 중 필수사항 입력

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#247]
sns선택을 안해도 승인요청하였습니다 라는 창이 뜹니다.
빨간 글씨 친 부분을 추가로 입력주세요!
계정정보 수정처럼 입력안했을 때 '필수사항을 입력해주세요'라고 먼저 뜨도록 해주세요

![233](https://cloud.githubusercontent.com/assets/22297543/23014303/ca0f4a60-f471-11e6-8157-e4638aa00f47.jpg)

**Comment by seobew** [comment]
완료.
