### ISSUE TITLE
문자 배열 오류 및 별점이 없어짐/로딩 느려짐

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#250]
![131](https://cloud.githubusercontent.com/assets/22297543/23018288/d2832374-f480-11e6-8dbb-86db94308b19.jpg)

1. 문자 배열이 이상해지고 로딩이 길어짐
2. 별점이 없어짐.
3. 상품 등록할 때 에디터 오류

**Comment by KangHyeongMin** [comment]
1. 로딩 느려지는 문제의 원인이 짐작은 가는데 그게 나머지 2,3에 영향을 줄지는 모르겠습니당 우선 로딩부터 해결해볼께용~
