### ISSUE TITLE
사진  crop비율설정 + 출생년도 기본값 수정

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#251]
![default](https://cloud.githubusercontent.com/assets/22297573/23019351/3110df72-f485-11e6-9277-4bc37d2ac3c8.jpeg)

출생연도 기본값은 1990년으로 해주시고 사진 크기같은 경우는 정사각형으로 잘릴 수 있게 해주세요! 사진이 찌그러져용 ㅠ

**Comment by KangHyeongMin** [comment]
동그라미 사진 문제는 제가 수정 중입니당~

**Comment by oooowljoy** [comment]
ㅋㅋㅋㅋ넹넹!

**Comment by KangHyeongMin** [comment]
수정했습니당 배포버전에서 적용되는지 확인 후에 닫을께요~
