### ISSUE TITLE
헷갈려요.정보수정 관련해서

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#253]
![ssss](https://cloud.githubusercontent.com/assets/22297573/23019455/ce2e9448-f485-11e6-9f69-08214c0d56b4.jpeg)

기본정보만 변경하고 현재 비밀번호 입력하니 정보는 바뀌었지만 
하단에 변경 비밀번호를 꼭 입력해야하는 것 처럼 되어있어서 불편해요.
기획이 필요할듯해요

**Comment by seobew** [comment]
완료.
