### ISSUE TITLE
상품등록 버튼 추가해주세요

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#256]
![jjj](https://cloud.githubusercontent.com/assets/22297573/23019655/c3924fba-f486-11e6-9a9a-8fb6e2ee83b9.jpeg)

이 페이지에 

![kk](https://cloud.githubusercontent.com/assets/22297573/23019657/c55377e8-f486-11e6-83b5-b7fbbc72e9f2.jpeg)

상품등록 버튼
추가해주세요! 위치는 멘트 하단에요!

**Comment by KangHyeongMin** [comment]
해결
