### ISSUE TITLE
블로그 유튜브 아이콘 크기 조절

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#278]
![11](https://cloud.githubusercontent.com/assets/22297543/23127448/6e529a06-f7be-11e6-9f39-a30e5b82de27.jpg)

블로그 유튜브 아이콘 크기가 작네요

**Comment by oooowljoy** [comment]
https://drive.google.com/open?id=0B_8MhWTWBP2FeEYwV1BPUHJqaUk
아이콘 교체했어요

**Comment by seobew** [comment]
완료.
