### ISSUE TITLE
리뷰 문자 배열

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#284]
![11](https://cloud.githubusercontent.com/assets/22297543/23152142/46d49274-f843-11e6-83aa-fcf8a04f3e72.jpg)

![11](https://cloud.githubusercontent.com/assets/22297543/23152194/b00c17da-f843-11e6-8288-88bc40fc3a90.jpg)

문자 배열 오류<특히 화면 작게 했을 때 너무 깨집니다>

**Comment by KangHyeongMin** [comment]
해결
