### ISSUE TITLE
구매, 판매 관리시 상품 링크연결

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#285]
![22](https://cloud.githubusercontent.com/assets/22297543/23152163/74e9cb20-f843-11e6-84fb-e4df0e36f7ac.jpg)

구매관리나 판매관리에 제가 구매한, 판매한 상품으로 바로 갈 수 있는게 없어서 불편합니다.
빨간 박스 클릭하면 해당 상품으로 가도록 해주세요

**Comment by seobew** [comment]
완료.
