### ISSUE TITLE
메시지에 사진이 안뜸

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#287]
![11](https://cloud.githubusercontent.com/assets/22297543/23152646/9bcd34f4-f846-11e6-8ee0-4cb834d75a09.jpg)
'
![11](https://cloud.githubusercontent.com/assets/22297543/23152729/64bae24e-f847-11e6-92d1-8af86033dc21.jpg)

문자배열과 사진이 안뜨네요

**Comment by KangHyeongMin** [comment]
해결. 배포 후 확인필요합니당
