### ISSUE TITLE
리뷰 문제

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#290]
![11](https://cloud.githubusercontent.com/assets/22297543/23153451/0c6a868a-f84c-11e6-9fe3-8a3e55f00883.jpg)

문제1. 세부평가 작성을 안해도 다 만족으로 나옵니다. 세부평가를 필수로 해주세요
문제2. 한줄 리뷰를 작성해도 none으로 뜹니다. 5자 이상 필수로 작성되도록 해주세요.
문제3. 5점을 했는데 안뜹니다.

**Comment by KangHyeongMin** [comment]
해결
