### ISSUE TITLE
Q&A에 추가 및 수정

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#299]
추가:
판매관련 카테고리로 넣어주세요.
Q. 소셜업의 수수료는 어떻게 되나요?
A. 소셜업의 수수료는 13%이며, 거래가 일어나는 건에 대해 수수료를 부과합니다.
예를 들어 총 판매가가 30,000원인 서비스가 판매되었을 때 13%인 3,900원을 뺀 25,100원이 포인트로 환산됩니다.
----------------------------------------------------------------------------------------------------
수정:
Q. 판매 수익금은 언제 포인트로 들어오나요?
A.
- 구매자가 구매 확정한 경우
구매자가 구매관리를 통해 서비스에 대한 구매를 확정한 후 1일 이내 수수료 13%를 제외한 결제 금액이 포인트로 전환됩니다.
- 구매자가 구매 확정을 하지 않은 경우
구매자가 구매 확정을 하지 않은 경우에는 거래완료일 기준  8일째 되는 날 자동으로 구매가 확정되며
1일 이내 수수료 13%를 제외한 결제 금액이 포인트로 전환됩니다.

---->여기서 8일째 되는 날이 아니라 7일째 되는 날로 수정

**Comment by seobew** [comment]
완료.
