### ISSUE TITLE
카테고리 선택안됨

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#302]
![22](https://cloud.githubusercontent.com/assets/22297543/23242498/623365a2-f9bc-11e6-9343-caf0b581b4dc.jpg)

그냥 전체-블로그-페이스북 탭 누르고 갈때는 나오는데
메인배너 누르고 갈때 카테고리 선택 다른 부분을 누르면 해당 서비스가 안나와요

**Comment by KangHyeongMin** [comment]
해결
