### ISSUE TITLE
계정 설정 사업자 부분 2

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#306]
![9](https://cloud.githubusercontent.com/assets/22297543/23245995/fc8faf4a-f9d3-11e6-991d-023e8aa9da0e.jpg)

입력하고 저장했는데 저장이 안됩니다.
![10](https://cloud.githubusercontent.com/assets/22297543/23246029/25b2d4a6-f9d4-11e6-9cee-36f757caef8f.jpg)

여기도 개인사업자라고 바뀌게 해주세요

등록안한 기본 판매자는 개인
관리자를 통해 인증받은 개인사업자는 개인사업자
관리자를 통해 인증받은 법인사업자는 법인사업자

**Comment by seobew** [comment]
완료.

**Comment by KangHyeongMin** [comment]
개인사업자,법인사업자로 체크하고 변경한 경우 내부적으로 '확인중'상태로 바뀌어서 저장됩니다. 확인중 상태일 때에는 체크내용이 보이지 않습니다. 기능상으로는 문제가 없지만 개선 여지가 있을 것 같아 확인 후 닫겠습니당
