### ISSUE TITLE
 팔로워1명당 표기

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#320]
![1](https://cloud.githubusercontent.com/assets/22297543/23346741/4a44768a-fce0-11e6-944f-14a269c32fb7.jpg)

지인들한테 물어보니 소셜업게이지를 설명해놓은 배너가 눈에 너무 안띈다고 하네요.
차라리 그래프에 표기하는게 나을것 같네요!
팔로워 1명당 이라고 써주세요

**Comment by KangHyeongMin** [comment]
완료
