### ISSUE TITLE
이미지교체!

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#322]
https://drive.google.com/open?id=0B_8MhWTWBP2FSVNNcmVGQ2M1MzA

**Comment by KangHyeongMin** [comment]
메인 처음에 나오는 부분에 교체해달라는거 맞죠? 뭐가 바뀐거예요? 해상도?

**Comment by oooowljoy** [comment]
글씨부분이 깨져서 이미지 출력 다시했어요!

**Comment by KangHyeongMin** [comment]
완료
