### ISSUE TITLE
홈페이지 하단에

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#325]
![1](https://cloud.githubusercontent.com/assets/22297543/23362782/bbab0618-fd3a-11e6-8e52-ef070070aeaa.jpg)

상호명 : 소셜업 
대표: 이수지
사업장 소재지 : 서울특별시 강남구 역삼동 770-10 한성빌딩 
사업자등록번호 : 483-15-00403      
통신판매업 신고 : 2016-서울서초-1612호 
이메일 : social_up@naver.com
Tel : 010-9505-2682

TEL 주소 바꼈어요!

**Comment by KangHyeongMin** [comment]
완료
