### ISSUE TITLE
0201_safari_issue

### ISSUE THREAD

**Issue by oooowljoy** [springkjw/socialup#83]
**(0)이미지 잘림,네비게이션없음, 드래그로 옮겨야함**
![bug_01](https://cloud.githubusercontent.com/assets/22297573/22505872/e1de6480-e8c0-11e6-8a6d-3e3b64115705.jpeg)

**(1)토끼 내려옴**
![bug_02](https://cloud.githubusercontent.com/assets/22297573/22505870/e1dbf150-e8c0-11e6-960c-310de3b56009.jpeg)

**(2)글자크기랑 아이콘크기 불균형, 이미지깨짐**
![bug_03](https://cloud.githubusercontent.com/assets/22297573/22505869/e1da2910-e8c0-11e6-863e-645298d61d6e.jpeg)

**(3)토끼내려옴**
![bug_04](https://cloud.githubusercontent.com/assets/22297573/22505873/e1dfc4d8-e8c0-11e6-9739-25b5b1552733.jpeg)

**(4)상단네비게이션?파란부분 정렬 안맞음**
![bug_05](https://cloud.githubusercontent.com/assets/22297573/22505871/e1de955e-e8c0-11e6-85a9-56d43a8e99dd.jpeg)

**Comment by seobew** [comment]
1,2,3,4 해결

**Comment by seobew** [comment]
socialup.kr에서 수정사항 확인했습니다.
