### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#85]
![1_](https://cloud.githubusercontent.com/assets/22297543/22538189/e615611e-e953-11e6-8aad-cbd2d5c1bc89.jpg)

1. 페이스북 로그인이 안됨.
2. 비밀번호를 잘못 입력했을 때나 메일을 잘못 입력했을 때 별도의 공지가 안뜸
![2](https://cloud.githubusercontent.com/assets/22297543/22538252/56305508-e954-11e6-99b1-119bd19c1771.jpg)
3.찜목록을 비롯해서 상품상세페이지 등 판매자와의 문의하기가 다 안됨
4. 서비스가 비뚤비뚤해요~
![3](https://cloud.githubusercontent.com/assets/22297543/22538288/a1eeaf58-e954-11e6-971e-b4f07030cc9e.jpg)
5. 해당사항으로 안내려감
![4](https://cloud.githubusercontent.com/assets/22297543/22538322/d62cfb8a-e954-11e6-97a8-4d487a020e54.jpg)
빨간 박스부분빼주세요

![6](https://cloud.githubusercontent.com/assets/22297543/22538347/05adae18-e955-11e6-9607-0b837b305c9d.jpg)
6. 여기서 비뚤비뚤하네요

![7](https://cloud.githubusercontent.com/assets/22297543/22538374/4d21e80e-e955-11e6-81d6-cb92aa20d353.jpg)

7. 네모칸 정리가 필요할듯해요
![8](https://cloud.githubusercontent.com/assets/22297543/22538403/7f4ae7d6-e955-11e6-9c72-7ecc20b8b392.jpg)

8. 전액포인트 결제해도 결제수단을 선택해야함
9. 밑에도 비뚤
![9](https://cloud.githubusercontent.com/assets/22297543/22538444/ae953b54-e955-11e6-810a-d21410d1356f.jpg)

10. 메인 검색쪽 글씨가 안맞아요
![11](https://cloud.githubusercontent.com/assets/22297543/22538455/d0d9c842-e955-11e6-929a-1c76128480e1.jpg)
11. 전체적으로 그래프가 다 이렇게 나와요
![12](https://cloud.githubusercontent.com/assets/22297543/22538495/11daeb28-e956-11e6-86e0-8020ca7a75db.jpg)

12.상품관리 페이지 클릭시 이렇게 나옴
![13](https://cloud.githubusercontent.com/assets/22297543/22538519/403c85b2-e956-11e6-9b98-5c46d3d3212c.jpg)

13. 글자가 이렇게 튀어나와있어요

**Comment by KangHyeongMin** [comment]
8. 전액포인트 결제해도 결제수단을 선택해야함 해결

**Comment by KangHyeongMin** [comment]
1. 페이스북 로그인이 안됨. 해결 (배포 서버에서 한번 더 확인 필요)

**Comment by KangHyeongMin** [comment]
3.찜목록을 비롯해서 상품상세페이지 등 판매자와의 문의하기가 다 안됨. 해결 (따로 수정한 부분이 없었는데 확인해보니 작동되는걸로 보입니다. 다양한 환경에서 다시한번 테스트 해볼께요)

**Comment by KangHyeongMin** [comment]
4-2. 빨간 박스부분빼주세요. 해결

**Comment by KangHyeongMin** [comment]
12.상품관리 페이지 클릭시 이렇게 나옴. (현재유저가 셀러가 아닐 경우 마이페이지 화면으로 다시 돌아가도록 해두었고, 셀러일 경우엔 문제없이 나옵니다. 크롬 외에 다른 브라우저에서 다시 테스트 해볼께요)

**Comment by seobew** [comment]
4, 13 해결.

**Comment by seobew** [comment]
2 해결

**Comment by KangHyeongMin** [comment]
나머지는 다 해결했고
6. 이슈 : 그래프 삐뚤빼뚤 => issue #138
7. 이슈 : 셀러정보 수정 인풋 사각형 맞추기 => issue #139
9. 이슈 : 결제시 결제방법 선택하면 네모 튀어나감 => issue #140
위와 같이 새 이슈로 넘기고 닫겠습니다.
