### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#86]
![default](https://cloud.githubusercontent.com/assets/22297543/22538557/95c2417a-e956-11e6-8bfc-6efc5374191c.jpg)
1. 상품등록페이지 하단에 스크롤바 없애주세요
![1](https://cloud.githubusercontent.com/assets/22297543/22538580/c24a6efc-e956-11e6-943e-aff94f4a642a.gif)
2. 상단에 위시리스트 장바구니- 요거 빼주시고 
화면 작게 보면 토끼가 저렇게 내려오네요
![2](https://cloud.githubusercontent.com/assets/22297543/22538627/2c2ed4e8-e957-11e6-8f65-5baa78601ac4.jpg)
3. sns바로가기 새창으로
4. 왼쪽 하단 글씨가 비뚤어요

**Comment by seobew** [comment]
1,2,3,4 해결

**Comment by seobew** [comment]
socialup.kr에서 수정한거 확인했습니다.
