### ISSUE TITLE
정보변경 후 페이지

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#94]
![1](https://cloud.githubusercontent.com/assets/22297543/22545490/4feaca70-e97c-11e6-9163-9761a6c4f62a.jpg)

정보변경후에 이런 페이지가 떠요

정보수정도 안되고요

![2](https://cloud.githubusercontent.com/assets/22297543/22545823/a75565e4-e97d-11e6-822b-dc288459ae41.jpg)

이렇게 팝업이 뜨도록 해주세요

**Comment by seobew** [comment]
완료.

**Comment by seobew** [comment]
socialup.kr에서 수정한거 확인했습니다.
