### ISSUE TITLE
정보수정-사업자

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#95]
![1](https://cloud.githubusercontent.com/assets/22297543/22545959/45acb274-e97e-11e6-8088-ac773297760b.jpg)

커서를 두면 none이 안없어져요. 정보수정도 안됩니다.

![2](https://cloud.githubusercontent.com/assets/22297543/22546009/7aca7086-e97e-11e6-9b72-a9f5521df850.jpg)

앞에 올렸던 정보수정과 마찬가지로 여기도 수정하고 이렇게 떠요
앞에 올렸던 것같은 팝업이 뜨게 해주세요

**Comment by seobew** [comment]
완료.

**Comment by seobew** [comment]
socialup.kr에서 수정한거 확인했습니다.
