### ISSUE TITLE
충전하기-vat빼주세요

### ISSUE THREAD

**Issue by ohleesuji** [springkjw/socialup#97]
![1](https://cloud.githubusercontent.com/assets/22297543/22546123/0a92812c-e97f-11e6-82b5-a25d893fbe4b.jpg)

10000원 충전하면 11000원이 아니라 10000원으로 되게 해주세요.
VAT는 위 금액에 이미 포함된 것으로

**Comment by KangHyeongMin** [comment]
해결. 빈센트가 배포버전에 적용 후 클로즈해주세요

**Comment by KangHyeongMin** [comment]
수정 적용된 것 확인했습니다.
